import { Patient } from "../types/patient";
export const data: Patient[] = [
	{
		id: "1",
		aptDate: "2025-01-15",
		aptTime: "10:00 AM",
		age: "52",
		gender: "Male",
		mrn: "11098",
		honorific: "Mr.",
		name: "William Pointing",
		email: "william.pointing@example.com",
		phone: "+1 (123) 456-7890",
		weight: "175",
		bloodGroup: "O+",
		risk: "High",
		noShow: "No",
		isScheduled: true,
		patientId: "11098 - William Pointing",
		a1: "success",
		a2: "success",
		a3: "success",
		a4: "not_available",
		a5: "success",
		a6: "warning",
		a7: "waiting",
		a8: "waiting",
		agentStatus: {
			agentStatusId: "escalated",
			agentStatus: "Escalated",
		},
		patientStatus: {
			patientStatusId: "pending",
			patientStatus: "Pending",
		},
		imageUrl: "https://i.ibb.co/wQj5BDN/image.png",
	},
	{
		id: "2",
		aptDate: "2025-01-15",
		aptTime: "11:30 AM",
		age: "45",
		gender: "Male",
		mrn: "11046",
		honorific: "Mr.",
		name: "James Gilchrist",
		email: "james.gilchrist@example.com",
		phone: "+1 (234) 567-8901",
		weight: "168",
		bloodGroup: "B+",
		risk: "Medium",
		noShow: "No",
		isScheduled: true,
		patientId: "11046 - James Gilchrist",
		a1: "success",
		a2: "success",
		a3: "success",
		a4: "success",
		a5: "warning",
		a6: "waiting",
		a7: "waiting",
		a8: "waiting",
		agentStatus: {
			agentStatusId: "work-in-progress",
			agentStatus: "Work in progress",
		},
		patientStatus: {
			patientStatusId: "pending",
			patientStatus: "Pending",
		},
		imageUrl: "https://i.ibb.co/TPMJFcx/image-copy.png",
	},
	{
		id: "3",
		aptDate: "2025-01-15",
		aptTime: "9:00 AM",
		age: "38",
		gender: "Male",
		mrn: "11025",
		honorific: "Mr.",
		name: "Michael Collins",
		email: "michael.collins@example.com",
		phone: "+1 (345) 678-9012",
		weight: "170",
		bloodGroup: "A-",
		risk: "Low",
		noShow: "No",
		isScheduled: true,
		patientId: "11025 - Michael Collins",
		a1: "success",
		a2: "success",
		a3: "success",
		a4: "failed",
		a5: "waiting",
		a6: "waiting",
		a7: "waiting",
		a8: "waiting",
		agentStatus: {
			agentStatusId: "completed",
			agentStatus: "Completed",
		},
		patientStatus: {
			patientStatusId: "scheduled",
			patientStatus: "Scheduled",
		},
		imageUrl: "https://i.ibb.co/2MMCZNL/image-copy-4.png",
	},
	{
		id: "4",
		aptDate: "2025-01-15",
		aptTime: "2:00 PM",
		age: "41",
		gender: "Male",
		mrn: "11048",
		honorific: "Mr.",
		name: "Nicholas Trump",
		email: "nicholas.trump@example.com",
		phone: "+1 (456) 789-0123",
		weight: "185",
		bloodGroup: "AB+",
		risk: "Medium",
		noShow: "No",
		isScheduled: true,
		patientId: "11048 - Nicholas Trump",
		a1: "success",
		a2: "success",
		a3: "success",
		a4: "not_available",
		a5: "waiting",
		a6: "waiting",
		a7: "waiting",
		a8: "waiting",
		agentStatus: {
			agentStatusId: "work-in-progress",
			agentStatus: "Work in progress",
		},
		patientStatus: {
			patientStatusId: "pending",
			patientStatus: "Pending",
		},
		imageUrl: "https://i.ibb.co/Lkr2QBX/image-copy-3.png",
	},
	{
		id: "5",
		aptDate: "2025-01-15",
		aptTime: "3:30 PM",
		age: "49",
		gender: "Male",
		mrn: "11020",
		honorific: "Mr.",
		name: "William Pointing",
		email: "william.p2@example.com",
		phone: "+1 (567) 890-1234",
		weight: "172",
		bloodGroup: "O-",
		risk: "High",
		noShow: "Yes",
		isScheduled: true,
		patientId: "11020 - William Pointing",
		a1: "success",
		a2: "success",
		a3: "failed",
		a4: "waiting",
		a5: "waiting",
		a6: "waiting",
		a7: "waiting",
		a8: "waiting",
		agentStatus: {
			agentStatusId: "escalated",
			agentStatus: "Escalated",
		},
		patientStatus: {
			patientStatusId: "pending",
			patientStatus: "Pending",
		},
		imageUrl: "https://i.ibb.co/BVHstk8/image-copy-2.png",
	},
	{
		id: "1",
		aptDate: "2025-01-15",
		aptTime: "10:00 AM",
		age: "52",
		gender: "Male",
		mrn: "11098",
		honorific: "Mr.",
		name: "William Pointing",
		email: "william.pointing@example.com",
		phone: "+1 (123) 456-7890",
		weight: "175",
		bloodGroup: "O+",
		risk: "High",
		noShow: "No",
		isScheduled: true,
		patientId: "11098 - William Pointing",
		a1: "success",
		a2: "success",
		a3: "success",
		a4: "not_available",
		a5: "success",
		a6: "warning",
		a7: "waiting",
		a8: "waiting",
		agentStatus: {
			agentStatusId: "escalated",
			agentStatus: "Escalated",
		},
		patientStatus: {
			patientStatusId: "pending",
			patientStatus: "Pending",
		},
		imageUrl: "https://i.ibb.co/wQj5BDN/image.png",
	},
	{
		id: "2",
		aptDate: "2025-01-15",
		aptTime: "11:30 AM",
		age: "45",
		gender: "Male",
		mrn: "11046",
		honorific: "Mr.",
		name: "James Gilchrist",
		email: "james.gilchrist@example.com",
		phone: "+1 (234) 567-8901",
		weight: "168",
		bloodGroup: "B+",
		risk: "Medium",
		noShow: "No",
		isScheduled: true,
		patientId: "11046 - James Gilchrist",
		a1: "success",
		a2: "success",
		a3: "success",
		a4: "success",
		a5: "warning",
		a6: "waiting",
		a7: "waiting",
		a8: "waiting",
		agentStatus: {
			agentStatusId: "work-in-progress",
			agentStatus: "Work in progress",
		},
		patientStatus: {
			patientStatusId: "pending",
			patientStatus: "Pending",
		},
		imageUrl: "https://i.ibb.co/TPMJFcx/image-copy.png",
	},
	{
		id: "3",
		aptDate: "2025-01-15",
		aptTime: "9:00 AM",
		age: "38",
		gender: "Male",
		mrn: "11025",
		honorific: "Mr.",
		name: "Michael Collins",
		email: "michael.collins@example.com",
		phone: "+1 (345) 678-9012",
		weight: "170",
		bloodGroup: "A-",
		risk: "Low",
		noShow: "No",
		isScheduled: true,
		patientId: "11025 - Michael Collins",
		a1: "success",
		a2: "success",
		a3: "success",
		a4: "failed",
		a5: "waiting",
		a6: "waiting",
		a7: "waiting",
		a8: "waiting",
		agentStatus: {
			agentStatusId: "completed",
			agentStatus: "Completed",
		},
		patientStatus: {
			patientStatusId: "scheduled",
			patientStatus: "Scheduled",
		},
		imageUrl: "https://i.ibb.co/2MMCZNL/image-copy-4.png",
	},
	{
		id: "4",
		aptDate: "2025-01-15",
		aptTime: "2:00 PM",
		age: "41",
		gender: "Male",
		mrn: "11048",
		honorific: "Mr.",
		name: "Nicholas Trump",
		email: "nicholas.trump@example.com",
		phone: "+1 (456) 789-0123",
		weight: "185",
		bloodGroup: "AB+",
		risk: "Medium",
		noShow: "No",
		isScheduled: true,
		patientId: "11048 - Nicholas Trump",
		a1: "success",
		a2: "success",
		a3: "success",
		a4: "not_available",
		a5: "waiting",
		a6: "waiting",
		a7: "waiting",
		a8: "waiting",
		agentStatus: {
			agentStatusId: "work-in-progress",
			agentStatus: "Work in progress",
		},
		patientStatus: {
			patientStatusId: "pending",
			patientStatus: "Pending",
		},
		imageUrl: "https://i.ibb.co/Lkr2QBX/image-copy-3.png",
	},
	{
		id: "5",
		aptDate: "2025-01-15",
		aptTime: "3:30 PM",
		age: "49",
		gender: "Male",
		mrn: "11020",
		honorific: "Mr.",
		name: "William Pointing",
		email: "william.p2@example.com",
		phone: "+1 (567) 890-1234",
		weight: "172",
		bloodGroup: "O-",
		risk: "High",
		noShow: "Yes",
		isScheduled: true,
		patientId: "11020 - William Pointing",
		a1: "success",
		a2: "success",
		a3: "failed",
		a4: "waiting",
		a5: "waiting",
		a6: "waiting",
		a7: "waiting",
		a8: "waiting",
		agentStatus: {
			agentStatusId: "escalated",
			agentStatus: "Escalated",
		},
		patientStatus: {
			patientStatusId: "pending",
			patientStatus: "Pending",
		},
		imageUrl: "https://i.ibb.co/BVHstk8/image-copy-2.png",
	},
	{
		id: "1",
		aptDate: "2025-01-15",
		aptTime: "10:00 AM",
		age: "52",
		gender: "Male",
		mrn: "11098",
		honorific: "Mr.",
		name: "William Pointing",
		email: "william.pointing@example.com",
		phone: "+1 (123) 456-7890",
		weight: "175",
		bloodGroup: "O+",
		risk: "High",
		noShow: "No",
		isScheduled: true,
		patientId: "11098 - William Pointing",
		a1: "success",
		a2: "success",
		a3: "success",
		a4: "not_available",
		a5: "success",
		a6: "warning",
		a7: "waiting",
		a8: "waiting",
		agentStatus: {
			agentStatusId: "escalated",
			agentStatus: "Escalated",
		},
		patientStatus: {
			patientStatusId: "pending",
			patientStatus: "Pending",
		},
		imageUrl: "https://i.ibb.co/wQj5BDN/image.png",
	},
	{
		id: "2",
		aptDate: "2025-01-15",
		aptTime: "11:30 AM",
		age: "45",
		gender: "Male",
		mrn: "11046",
		honorific: "Mr.",
		name: "James Gilchrist",
		email: "james.gilchrist@example.com",
		phone: "+1 (234) 567-8901",
		weight: "168",
		bloodGroup: "B+",
		risk: "Medium",
		noShow: "No",
		isScheduled: true,
		patientId: "11046 - James Gilchrist",
		a1: "success",
		a2: "success",
		a3: "success",
		a4: "success",
		a5: "warning",
		a6: "waiting",
		a7: "waiting",
		a8: "waiting",
		agentStatus: {
			agentStatusId: "work-in-progress",
			agentStatus: "Work in progress",
		},
		patientStatus: {
			patientStatusId: "pending",
			patientStatus: "Pending",
		},
		imageUrl: "https://i.ibb.co/TPMJFcx/image-copy.png",
	},
	{
		id: "3",
		aptDate: "2025-01-15",
		aptTime: "9:00 AM",
		age: "38",
		gender: "Male",
		mrn: "11025",
		honorific: "Mr.",
		name: "Michael Collins",
		email: "michael.collins@example.com",
		phone: "+1 (345) 678-9012",
		weight: "170",
		bloodGroup: "A-",
		risk: "Low",
		noShow: "No",
		isScheduled: true,
		patientId: "11025 - Michael Collins",
		a1: "success",
		a2: "success",
		a3: "success",
		a4: "failed",
		a5: "waiting",
		a6: "waiting",
		a7: "waiting",
		a8: "waiting",
		agentStatus: {
			agentStatusId: "completed",
			agentStatus: "Completed",
		},
		patientStatus: {
			patientStatusId: "scheduled",
			patientStatus: "Scheduled",
		},
		imageUrl: "https://i.ibb.co/2MMCZNL/image-copy-4.png",
	},
	{
		id: "4",
		aptDate: "2025-01-15",
		aptTime: "2:00 PM",
		age: "41",
		gender: "Male",
		mrn: "11048",
		honorific: "Mr.",
		name: "Nicholas Trump",
		email: "nicholas.trump@example.com",
		phone: "+1 (456) 789-0123",
		weight: "185",
		bloodGroup: "AB+",
		risk: "Medium",
		noShow: "No",
		isScheduled: true,
		patientId: "11048 - Nicholas Trump",
		a1: "success",
		a2: "success",
		a3: "success",
		a4: "not_available",
		a5: "waiting",
		a6: "waiting",
		a7: "waiting",
		a8: "waiting",
		agentStatus: {
			agentStatusId: "work-in-progress",
			agentStatus: "Work in progress",
		},
		patientStatus: {
			patientStatusId: "pending",
			patientStatus: "Pending",
		},
		imageUrl: "https://i.ibb.co/Lkr2QBX/image-copy-3.png",
	},
	{
		id: "5",
		aptDate: "2025-01-15",
		aptTime: "3:30 PM",
		age: "49",
		gender: "Male",
		mrn: "11020",
		honorific: "Mr.",
		name: "William Pointing",
		email: "william.p2@example.com",
		phone: "+1 (567) 890-1234",
		weight: "172",
		bloodGroup: "O-",
		risk: "High",
		noShow: "Yes",
		isScheduled: true,
		patientId: "11020 - William Pointing",
		a1: "success",
		a2: "success",
		a3: "failed",
		a4: "waiting",
		a5: "waiting",
		a6: "waiting",
		a7: "waiting",
		a8: "waiting",
		agentStatus: {
			agentStatusId: "escalated",
			agentStatus: "Escalated",
		},
		patientStatus: {
			patientStatusId: "pending",
			patientStatus: "Pending",
		},
		imageUrl: "https://i.ibb.co/BVHstk8/image-copy-2.png",
	},
];
